# Generated by Django 4.2.5 on 2025-07-19 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('myapp', '0001_initial'), ('myapp', '0002_book_delete_mymodel'), ('myapp', '0003_alter_book_title')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('pages', models.IntegerField(default=0)),
            ],
        ),
    ]
